In [20]:
import pandas as pd

In [21]:
df=pd.read_csv('match_events.csv')
##fetch the first 5 rows
df.head(5)

   event_id  match_id  minute   event_type  team_id  player_id
0         1         1       9         Goal        1         16
1         2         1       9       Assist        1          6
2         3         1      17  Yellow Card        2         30
3         4         1      23  Yellow Card        1         26
4         5         1      55     Red Card        2         39

In [22]:
df.tail(5)

     event_id  match_id  minute   event_type  team_id  player_id
578       579        76      71  Yellow Card       21        525
579       580        76      72         Goal       21        531
580       581        76      72       Assist       21        544
581       582        76      90         Goal       10        248
582       583        76      90       Assist       10        241

In [23]:
df.describe()

         event_id    match_id      minute     team_id    player_id
count  583.000000  583.000000  583.000000  583.000000   583.000000
mean   292.000000   38.092624   53.397942   23.411664   596.001715
std    168.441879   22.276650   27.684889   13.455233   349.725688
min      1.000000    1.000000    2.000000    1.000000     2.000000
25%    146.500000   19.000000   32.000000   12.000000   291.000000
50%    292.000000   38.000000   55.000000   22.000000   570.000000
75%    437.500000   57.000000   78.000000   35.000000   894.000000
max    583.000000   76.000000  120.000000   48.000000  1239.000000

In [24]:
df.dtypes

event_id       int64
match_id       int64
minute         int64
event_type    object
team_id        int64
player_id      int64
dtype: object

In [25]:
##handling missing values
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
578    False
579    False
580    False
581    False
582    False
Length: 583, dtype: bool

In [26]:
df.isnull().sum()

event_id      0
match_id      0
minute        0
event_type    0
team_id       0
player_id     0
dtype: int64

In [27]:
df.fillna(0)

     event_id  match_id  minute   event_type  team_id  player_id
0           1         1       9         Goal        1         16
1           2         1       9       Assist        1          6
2           3         1      17  Yellow Card        2         30
3           4         1      23  Yellow Card        1         26
4           5         1      55     Red Card        2         39
..        ...       ...     ...          ...      ...        ...
578       579        76      71  Yellow Card       21        525
579       580        76      72         Goal       21        531
580       581        76      72       Assist       21        544
581       582        76      90         Goal       10        248
582       583        76      90       Assist       10        241

[583 rows x 6 columns]

In [28]:
## ranaming columns
df=df.rename(columns={"minute":"minute_time"})

df.head()

   event_id  match_id  minute_time   event_type  team_id  player_id
0         1         1            9         Goal        1         16
1         2         1            9       Assist        1          6
2         3         1           17  Yellow Card        2         30
3         4         1           23  Yellow Card        1         26
4         5         1           55     Red Card        2         39

In [34]:
#change datatype
df["player_number"]=df["player_id"].astype(float)

df.head()

,event_id,match_id,minute_time,event_type,team_id,player_id,player_number
0,1,1,9,Goal,1,16,16.0
1,2,1,9,Assist,1,6,6.0
2,3,1,17,Yellow Card,2,30,30.0
3,4,1,23,Yellow Card,1,26,26.0
4,5,1,55,Red Card,2,39,39.0

In [36]:
#data aggreating and grouping

grouped_mean=df.groupby('event_id')['player_id'].mean()
print (grouped_mean)

event_id
1       16.0
2        6.0
3       30.0
4       26.0
5       39.0
       ...
579    525.0
580    531.0
581    544.0
582    248.0
583    241.0
Name: player_id, Length: 583, dtype: float64

In [37]:
grouped_sum=df.groupby(["event_id","event_type"])["minute_time"].sum()
print (grouped_sum)

event_id  event_type
1         Goal            9
2         Assist          9
3         Yellow Card    17
4         Yellow Card    23
5         Red Card       55
                         ..
579       Yellow Card    71
580       Goal           72
581       Assist         72
582       Goal           90
583       Assist         90
Name: minute_time, Length: 583, dtype: int64

In [38]:
df.groupby(["event_id","event_type"])["minute_time"].mean()

event_id  event_type
1         Goal            9.0
2         Assist          9.0
3         Yellow Card    17.0
4         Yellow Card    23.0
5         Red Card       55.0
                         ...
579       Yellow Card    71.0
580       Goal           72.0
581       Assist         72.0
582       Goal           90.0
583       Assist         90.0
Name: minute_time, Length: 583, dtype: float64

In [39]:
##multipal aggregate function
groouped_age=df.groupby("event_id")["team_id"].agg(['mean','sum','count'])
groouped_age

          mean  sum  count
event_id
1          1.0    1      1
2          1.0    1      1
3          2.0    2      1
4          1.0    1      1
5          2.0    2      1
...        ...  ...    ...
579       21.0   21      1
580       21.0   21      1
581       21.0   21      1
582       10.0   10      1
583       10.0   10      1

[583 rows x 3 columns]

In [42]:
## meargin and joinning dataframes
df1=pd.DataFrame({'Key': ["a", "b",'c'], "Value1": [1,2,3]})
df2=pd.DataFrame({'Key': ["d", "e","f"], "Value2": [4,5,6]})

In [43]:
df1

  Key  Value1
0   a       1
1   b       2
2   c       3

In [44]:
df2

  Key  Value2
0   d       4
1   e       5
2   f       6

In [46]:
##merge dataframe on the key collum
pd.merge(df1,df2,on="Key",how="inner")

Empty DataFrame
Columns: [Key, Value1, Value2]
Index: []

In [47]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   a     1.0     NaN
1   b     2.0     NaN
2   c     3.0     NaN
3   d     NaN     4.0
4   e     NaN     5.0
5   f     NaN     6.0

In [49]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   d     NaN       4
1   e     NaN       5
2   f     NaN       6

In [50]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   a       1     NaN
1   b       2     NaN
2   c       3     NaN